title: Page
fields:
  title:
    label: Title
    type:  text
    
  text:
    label: Text (left)
    type:  textarea

  intro:
    label: Text (bottom)
    type:  textarea

files:
  fields:
    caption:
      label: Caption
      type: textarea