title: Page

fields:
  title:
    label: Title
    type:  text

  intro:
    label: Intro
    type:  textarea
    
  text:
    label: Text
    type:  textarea

files:
  fields:
    caption:
      label: Caption
      type: textarea