title: Pagina
pages: false
fields:
  title:
    label: Titel
    type:  text
    
  text:
    label: Tekst links
    type:  textarea

  intro:
    label: Tekst onderaan
    type:  textarea

files:
  fields:
    caption:
      label: Onderschrift
      type: textarea